// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/GearSetCenter.h"
#include "Commands/GearSetLeft.h"
#include "Commands/GearSetRight.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    gearJoy.reset(new Joystick(0));
    
    gearRightButton.reset(new JoystickButton(gearJoy.get(), 1));
    gearRightButton->WhenPressed(new GearSetRight());
    gearLeftButton.reset(new JoystickButton(gearJoy.get(), 3));
    gearLeftButton->WhenPressed(new GearSetLeft());
    gearCenterButton.reset(new JoystickButton(gearJoy.get(), 2));
    gearCenterButton->WhenPressed(new GearSetCenter());

    // SmartDashboard Buttons
    SmartDashboard::PutData("GearSetRight", new GearSetRight());
    SmartDashboard::PutData("GearSetLeft", new GearSetLeft());
    SmartDashboard::PutData("GearSetCenter", new GearSetCenter());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getGearJoy() {
   return gearJoy;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
